# Generated by Django 4.2.1 on 2023-05-31 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockie_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_consumer',
        ),
    ]
